### ISSUE TITLE
gems error.

### ISSUE THREAD

**Issue by ghost** [solojavier/mi-trabajo-ideal#3]
I have a problem for run rails.

I have installed rails and ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15] but when run "rails -v" the console return me the next error:

```
Your Ruby version is 2.0.0, but your gamfile specified 2.2.3
```

i did write the command "gem install rails" and the console continues to throw the error

**Comment by ghost** [comment]
Annex consulted sites<

https://gorails.com/setup/osx/10.11-el-capitan
https://github.com/rbenv/rbenv#rbenv-shell

**Comment by solojavier** [comment]
If you have rbenv installed run the following commands:

```
rbenv install 2.2.3
rbenv shell 2.2.3
```

Now if you run:

```
 rbenv version
```

It must give you the correct version and you could try to run rails command again.

**Comment by ghost** [comment]
Now the error is as follows.

`/users/test/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.0.1/lib/rails/app_loader.rb:40: warning: Insecure world writable dir /usr/local/Cellar in PATH, mode 040777
Your bundle is locked to json (1.8.3), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of json (1.8.3) has removed it. You'll need to update your bundle to a different version of json (1.8.3) that hasn't been removed in order to install.
Run`bundle install`to install missing gems.`

This has already happened to me, I run bundle install, I throw the following error.

`An error occurred while installing nokogiri (1.6.6.2), and Bundler
cannot continue.
Make sure that`gem install nokogiri -v '1.6.6.2'`succeeds before bundling.`

I then execute ´gem install nokogiri -v '1.6.6.2 ´ and your answer is 

`extconf failed, exit code 1`

**Comment by ghost** [comment]
Building native extensions.  This could take a while...
/Users/test/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/ext/builder.rb:73: warning: Insecure world writable dir /usr/local/Cellar in PATH, mode 040777
ERROR:  Error installing nokogiri:
    ERROR: Failed to build gem native extension.

   /Users/test/.rbenv/versions/2.2.3/bin/ruby -r ./siteconf20161108-78507-j8nk2y.rb extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no

## Building nokogiri using packaged libraries.

The file "/usr/include/iconv.h" is missing in your build environment,
which means you haven't installed Xcode Command Line Tools properly.

To install Command Line Tools, try running `xcode-select --install` on
terminal and follow the instructions.  If it fails, open Xcode.app,
select from the menu "Xcode" - "Open Developer Tool" - "More Developer
Tools" to open the developer site, download the installer for your OS

## version and run it.

**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/test/.rbenv/versions/2.2.3/bin/$(RUBY_BASE_NAME)
    --help
    --clean
    --use-system-libraries
    --enable-static
    --disable-static
    --with-zlib-dir
    --without-zlib-dir
    --with-zlib-include
    --without-zlib-include=${zlib-dir}/include
    --with-zlib-lib
    --without-zlib-lib=${zlib-dir}/lib
    --enable-cross-build
    --disable-cross-build

extconf failed, exit code 1

Gem files will remain installed in /Users/test/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /Users/test/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.6.6.2/gem_make.out

**Comment by solojavier** [comment]
Try this to see if that helps: https://teamtreehouse.com/community/extconf-failed-exit-code-1-cant-install-rails-due-to-this-error-help-plz
