### ISSUE TITLE
Error with data base.

### ISSUE THREAD

**Issue by ghost** [solojavier/mi-trabajo-ideal#4]
I restarted the app and when i runned the app, the server showed me the next status.

`could not connect to server: Connection refused Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432`

But, i don't know what happend!

**Comment by solojavier** [comment]
Ya buscaste en google?

Así de rápido encontre esto: http://stackoverflow.com/questions/13410686/postgres-could-not-connect-to-server

**Comment by ghost** [comment]
Si, todo va a lo que te comentaba. Tengo un mal ambiente de desarrollo de Ruby y Postgres. Me di cuenta que cuando reinicio el server de rails se cayó toda la configuración.

Instale RVM e instale con rvm la versión de Ruby 2.2.3, posterior a eso borre todo temporal de postgres y reinstale postgres después de tener lo de Ruby y rails solucionado.
